# **A simple neural network making a prediction**

In [12]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [13]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


# **Making a prediction with multiple inputs**

In [14]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range (len(a)):
        output += (a[i] * b[i])
        
    return output

In [15]:
weights = [0.1, 0.2, 0]
def neural_network2(input, weights):
    pred = w_sum(input, weights)
    return pred

In [16]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network2(input, weights)
print(pred)

0.9800000000000001


### Challenge: Vector Math

In [6]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] * vec_b[i])
    return output

In [13]:
a = [1,2,3,4]
b = [5,6,7,8]
print(elementwise_multiplication(a,b))

[5, 12, 21, 32]


In [10]:
def elementwise_addition(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] + vec_b[i])
    return output

In [14]:
a = [1,2,3,4]
b = [5,6,7,8]
print(elementwise_addition(a,b))

[6, 8, 10, 12]


In [12]:
def vector_sum(vec_a):
    output = 0
    for i in range(len(vec_a)):
        output += vec_a[i]
    return output

In [15]:
a = [1,2,3,4]
print(vector_sum(a))

10


In [16]:
def vector_average(vec_a):
    return vector_sum(vec_a) / len(vec_a)

In [17]:
a = [1,2,3,4]
print(vector_average(a))

2.5


In [20]:
def dot_product(vec_a, vec_b):
    return vector_sum(elementwise_multiplication(vec_a, vec_b))

In [21]:
a = [1,2,3,4]
b = [5,6,7,8]
print(dot_product(a,b))

70


# Multiple Inputs using NumPy

In [22]:
import numpy as np
weights = np.array([0.1, 0.2, 0])
def neural_network3(input, weights):
    pred = input.dot(weights)
    return pred

In [23]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network3(input, weights)
print(pred)

0.9800000000000001


# Making a Prediction with Multiple Outputs

In [25]:
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

In [26]:
weights = [0.3, 0.2, 0.9]
def neural_network4(input, weights):
    pred = ele_mul(input, weights)
    return pred

In [27]:
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network4(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


# Predicting with Multiple Inputs and Outputs

In [28]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

In [29]:
def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

In [30]:
weights = [ [0.1, 0.1, -0.3],
            [0.1, 0.2, 0.0],
            [0.0, 1.3, 0.1] ]
def neural_network5(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

In [31]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network5(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


# Using Hidden Layers

In [32]:
ih_wgt = [ [0.1, 0.2, -0.1],
           [-0.1, 0.1, 0.9],
           [0.1, 0.4, 0.1] ]
hp_wgt = [ [0.3, 1.1, -0.3],
           [0.1, 0.2, 0.0],
           [0.0, 1.3, 0.1] ]
weights = [ih_wgt, hp_wgt]

def neural_network6(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

In [33]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network6(input, weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


# Hidden Layers done with NumPy

In [43]:
import numpy as np
ih_wgt = np.array([
            [0.1, 0.2, -0.1],
            [-0.1, 0.1, 0.9],
            [0.1, 0.4, 0.1] 
            ])
hp_wgt = np.array([
            [0.3, 1.1, -0.3],
            [0.1, 0.2, 0.0],
            [0.0, 1.3, 0.1] 
            ])
weights = np.array([ih_wgt, hp_wgt])

def neural_network7(input, weights):
    hid = weights[0].dot(input)
    pred = weights[1].dot(hid)
    return pred

In [44]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network7(input, weights)
print(pred)

[0.2135 0.145  0.5065]


# NumPy Primer

In [2]:
import numpy as np

a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
             [4,5,6,7]])

d = np.zeros((2,4))
e = np.random.rand(2,5)

print(a * 0.1)      # Multiplies every number in vector by 0.1
print(c * 0.2)      # Multiplies every number in matrix by 0.2
print(a * b)        # Multiplies elementwise between a and b (columns paired)
print(a * b * 0.2)  # Multiplies elementwise, then multiplies by 0.2
print(a * c)        # Performs elementwise multiplication on every row of matrix c, 
                    #  because c has the same number of columns as a
#print(a * e)       # Error

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]
